In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [ ]:
filepath = "/KaggleImbalanced.csv"
df = pd.read_csv(filepath)
df

Source.IP  Source.Port  Destination.IP  Destination.Port  Protocol  \
0       2.886927e+09      52422.0    1.808812e+08            3128.0       6.0   
1       1.808812e+08       3128.0    2.886927e+09           52422.0       6.0   
2       8.409398e+08         80.0    1.808814e+08           38848.0       6.0   
3       8.409398e+08         80.0    1.808814e+08           38848.0       6.0   
4       3.232254e+09      55961.0    1.808812e+08            3128.0       6.0   
...              ...          ...             ...               ...       ...   
115639  1.808812e+08       3128.0    3.232292e+09           54981.0       6.0   
115640  3.232244e+09      59437.0    1.808812e+08            3128.0       6.0   
115641  1.808813e+08      51821.0    3.222287e+09             443.0       6.0   
115642  1.808812e+08       3128.0    2.886861e+09           60445.0       6.0   
115643  3.232282e+09      50807.0    1.808812e+08            3128.0       6.0   

        Flow.Duration  Total.Fwd.Packets  Total.Backward.Packets  \
0             45523.0               22.0                    55.0   
1                 1.0                2.0                     0.0   
2                 1.0                3.0                     0.0   
3               217.0                1.0                     3.0   
4             78068.0                5.0                     0.0   
...               ...                ...                     ...   
115639           91.0                4.0                     2.0   
115640          483.0                1.0                    10.0   
115641        34833.0                4.0                     3.0   
115642          158.0                4.0                     0.0   
115643          244.0                1.0                     4.0   

        Total.Length.of.Fwd.Packets  Total.Length.of.Bwd.Packets  ...  \
0                             132.0                     110414.0  ...   
1                              12.0                          0.0  ...   
2                             674.0                          0.0  ...   
3                               0.0                          0.0  ...   
4                            1076.0                          0.0  ...   
...                             ...                          ...  ...   
115639                         24.0                         12.0  ...   
115640                          6.0                         60.0  ...   
115641                        206.0                        301.0  ...   
115642                         24.0                          0.0  ...   
115643                          6.0                         24.0  ...   

        Active.Mean  Active.Std  Active.Max  Active.Min  Idle.Mean  Idle.Std  \
0               0.0         0.0         0.0         0.0        0.0       0.0   
1               0.0         0.0         0.0         0.0        0.0       0.0   
2               0.0         0.0         0.0         0.0        0.0       0.0   
3               0.0         0.0         0.0         0.0        0.0       0.0   
4               0.0         0.0         0.0         0.0        0.0       0.0   
...             ...         ...         ...         ...        ...       ...   
115639          0.0         0.0         0.0         0.0        0.0       0.0   
115640          0.0         0.0         0.0         0.0        0.0       0.0   
115641          0.0         0.0         0.0         0.0        0.0       0.0   
115642          0.0         0.0         0.0         0.0        0.0       0.0   
115643          NaN         NaN         NaN         NaN        NaN       NaN   

        Idle.Max  Idle.Min  L7Protocol  ProtocolName  
0            0.0       0.0       131.0    HTTP_PROXY  
1            0.0       0.0       131.0    HTTP_PROXY  
2            0.0       0.0         7.0          HTTP  
3            0.0       0.0         7.0          HTTP  
4            0.0       0.0       131.0    HTTP_PROXY  
...          ...       ...         ...           ... 

In [ ]:
df = df.drop(df.index[-1])

In [ ]:
feats = [x for x in df.columns if x != 'ProtocolName']
X = df[feats]
Y = df['ProtocolName']

In [ ]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 42)

In [ ]:
params = { 'n_neighbors': [3, 5, 7, 11, 21],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan'] }
gs = GridSearchCV(KNeighborsClassifier(), params, cv = 10, n_jobs = -1)

In [ ]:
neigh = KNeighborsClassifier(n_neighbors = 3, metric='manhattan', weights='distance')

In [ ]:
%%time
neigh.fit(X_train, y_train)

CPU times: user 137 ms, sys: 0 ns, total: 137 ms
Wall time: 145 ms


KNeighborsClassifier(metric='manhattan', n_neighbors=3, weights='distance')

In [ ]:

%%time
neigh.score(X_test, y_test)

CPU times: user 9min 6s, sys: 406 ms, total: 9min 6s
Wall time: 5min 3s


0.8781598593376185

In [ ]:
%%time
y_pred = neigh.predict(X_test)

CPU times: user 9min 6s, sys: 417 ms, total: 9min 7s
Wall time: 5min 15s


In [ ]:
print(classification_report(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

                precision    recall  f1-score   support

        AMAZON       0.85      0.79      0.82       453
         APPLE       1.00      0.33      0.50         6
  APPLE_ICLOUD       0.25      0.12      0.17         8
  APPLE_ITUNES       0.00      0.00      0.00         8
    CLOUDFLARE       0.95      0.85      0.90       110
 CONTENT_FLASH       0.98      1.00      0.99       128
           DNS       1.00      0.83      0.91         6
       DROPBOX       0.80      0.83      0.81       179
          EBAY       0.57      0.40      0.47        10
      FACEBOOK       0.87      0.84      0.86       187
         GMAIL       0.49      0.23      0.32       337
        GOOGLE       0.81      0.88      0.84      7793
   GOOGLE_MAPS       0.00      0.00      0.00         2
          HTTP       0.99      0.98      0.98     11579
  HTTP_CONNECT       0.79      0.79      0.79      2557
 HTTP_DOWNLOAD       0.75      0.38      0.50         8
    HTTP_PROXY       0.86      0.87      0.86  

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[360   0   0 ...   1   1   2]
 [  0   2   0 ...   0   0   0]
 [  0   0   1 ...   0   2   0]
 ...
 [  1   0   0 ... 301   0   4]
 [  1   0   0 ...   0  92   3]
 [  1   0   0 ...   0   0 713]]
